#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

declare -A version
version=(["php53"]="PHP 5.3.29" ["php56"]="PHP 5.5.90" ["php7.1"]="PHP 7.1.11")

apache="/var/run/apache2/apache2.pid"
old=""
new=""

for key in "${!version[@]}"; do
  options+=("${version[$key]}")
done

if a2query -m php5  |& grep -q "[e]nabled" ; then old="php56";  fi
if a2query -m php53 |& grep -q "[e]nabled" ; then old="php53"; fi
if a2query -m php7.1 |& grep -q "[e]nabled" ; then old="php7.1";  fi

if [ -e "$apache" ]
then
    running="started"
    op="/etc/init.d/apache2 restart"
else
    running="stopped"
    op="/etc/init.d/apache2 start"
fi

oldname="${version[$old]}"
echo "Apache is $running. Current PHP mod: $oldname"

i=0
for key in "${!version[@]}"; do
  ((i++))
  echo "$i) ${version[$key]}"   
  options+=("${version[$key]}")
done

read -p "Enter your name : " option

i=0
for key in "${!version[@]}"; do
  ((i++))
  if [[ "$option" -eq "$i" ]]
  then
    new=$key
  fi
done

if [[ $new == "" ]] 
then
  echo "invalid option"
  exit 1
fi 

newname="${version[${new}]}"

if [[ $new != $old ]]
then
    a2enmod $new
    a2dismod $old
    rm /etc/alternatives/php 
    ln -s /usr/bin/$new /etc/alternatives/php
    echo "Successfully switched to $newname"
else
    echo "Keeping current version of PHP ($oldname)"
    exit
fi

$op

if  ! [[ -e "$apache" ]]
then
    echo "An error occured, check the apache log"
    exit 1
fi
